tasks:
  - name: Start k3s and Argo CD
    init: |
      curl -sfL https://get.k3s.io -o install.sh
      chmod +x install.sh
      INSTALL_K3S_SKIP_ENABLE=true INSTALL_K3S_SKIP_START=true ./install.sh
      sudo /usr/local/bin/k3s server > /tmp/k3s.log 2>&1 &
      export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
      echo "Waiting for Kubernetes API..."
      until kubectl get nodes; do sleep 2; done
      kubectl create namespace argocd
      kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml --validate=false
      sleep 20
      kubectl apply -f argocd/app.yaml --validate=false
    command: |
      export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
      echo "Use this to port-forward ArgoCD:"
      echo "kubectl port-forward svc/argocd-server -n argocd 8080:443"
      bash
